== Fulcro Native Template

This branch contains a Fulcro setup into which
a React Native raw project (not expo) can be injected.

The basic idea is this:

top-level
  * Clojure(script) project with source for server, web, and mobile
  * React Native project lives in subdirectory `mobile`

The top-level project emits js INTO the mobile directory, which
is otherwise completely controlled by the React Native ecosystem.

== Prerequisites

Clojure
https://clojure.org/guides/install_clojure

== Basic Usage

First, clone this branch as a template. You'll then need to create a new react native project as a subdirectory
according to the instructions below.

=== Create the mobile app

This repo does NOT have the mobile app set up so that you're not working with some out-of-date React Native stuff.

Follow the CURRENT directions from React Native's website https://reactnative.dev/docs/environment-setup[React Native Environment Setup],
and follow the instructions for working with React Native CLI (NOT EXPO).

At the time of this writing, that basically boiled down to installing XCode and command line utilities, watchman
making sure your node version was reasonable (e.g. use NVM with version 18) and then generating the project:

[source, bash]
-----
$ npx react-native@latest init mobile
-----

NOTE: Do this IN the project's directory, and name your mobile app "mobile" so it will make a `mobile` subdirectory.
The cljs compile will want to find it there for js output.

=== Touch up the Generated App

In the `mobile` directory

remove `App.jsx` and `index.js`. You'll be using shadow-cljs to generate the js.

You will also need to add react-dom, even though you don't actually render dom.
This is because parts of Fulcro refer to that package internally, though they will not
invoke it for native:

[source, bash]
-----
$ yarn add react-dom
-----

=== Build the CLJS:

Now back in the TOP level directory (not mobile) , start up CLJS build:

[source, bash]
-----
$ yarn
$ npx shadow-cljs server
-----

Go to http://localhost:9630/dashboard and
click on Builds, and check the native
and web builds (you should see both of them
build).

Make sure you have the clojure CLI tools
installed, start a CLJ REPL:

[source, bash]
-----
$ clj -A:dev
user=> (require 'development)
user=> (development/start)
-----

You should see a message about starting.

Open http://localhost:3000. This is the webapp.

For mobile version
In another terminal, start up metro on an iOS simulator:

[source, bash]
-----
$ cd mobile
$ yarn ios
-----

An iPad/Phone simulator should start with the app.

You will probably need to update `shadow-cljs.edn` to set URLs for inspect and the server. `localhost` will generally
not work, since the mobile device itself has such an address.
The host machine is always 10.0.2.2 for the Android Studio emulator, and you can typically use `ifconfig | grep 192`
to find your server machine's current IP on your local router.

[source]
-----
:closure-defines  {'goog.DEBUG                  true
                    app.client-native/SERVER_URL "http://10.0.2.2:3000/api-native"
                    com.fulcrologic.fulcro.inspect.inspect_ws/SERVER_PORT 8237
                    com.fulcrologic.fulcro.inspect.inspect_ws/SERVER_HOST "10.0.2.2"}
-----

== Using Inspect

Just start Fulcro Inspect electron app before running your mobile app.
It should work out of the box and the app should auto-connect.
If you have problem connecting try "r" in metro menu or restarting the mobile simulator

IMPORTANT: By default native app will try to connect to Electron Fulcro Inspect.
You may comment out the app.inspect-native-preload in `shadow-cljs.edn` to disable this. If you don't have
Inspect running you'll see an error about unable to connect to it once a second in the metro logs.

NOTE: Logging errors in the Native env will show
an error screen on the app. Just press ESC to
continue in the simulator if that happens.

